CREATE DATABASE IF NOT EXISTS cloudfly_db;
USE cloudfly_db;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    profile_image VARCHAR(255) DEFAULT NULL,
    current_storage BIGINT DEFAULT 0,
    reserved_storage BIGINT DEFAULT 0,
    max_storage BIGINT DEFAULT 10737418240,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE reset_password_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    expiration_date DATETIME NOT NULL,
    user INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE folders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner INT NOT NULL,
    parent INT DEFAULT NULL,
    name VARCHAR(50) NOT NULL,
    path VARCHAR(1024) DEFAULT '/',
    is_starred BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (parent) REFERENCES folders(id) ON DELETE SET NULL
);

CREATE TABLE files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner INT NOT NULL,
    parent INT DEFAULT NULL,
    uuid VARCHAR(255) UNIQUE NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    current_version INT DEFAULT NULL,
    current_size BIGINT NOT NULL,
    current_mime_type VARCHAR(100) NOT NULL,
    current_type VARCHAR(50) NOT NULL,
    public_key VARCHAR(255) DEFAULT NULL,
    is_starred BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (parent) REFERENCES folders(id) ON DELETE SET NULL
);

CREATE TABLE file_versions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file INT NOT NULL,
    storage_key VARCHAR(255) UNIQUE NOT NULL,
    version INT NOT NULL,
    size BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (file) REFERENCES files(id) ON DELETE CASCADE
);